image: onaio/python:2.7
services:
    - onaio/postgis
    - onaio/mongodb
script:
    - ./script/database/install_postgis onadata_test postgres 127.0.0.1
    - ./script/install/ubuntu
    - pip install -qr requirements/base.pip --allow-all-external
    - pip install -q flake8
    - python manage.py syncdb --noinput --settings=onadata.settings.drone_test
    - python manage.py migrate --noinput --settings=onadata.settings.drone_test
    - python manage.py test --noinput --settings=onadata.settings.drone_test
