sudo: required
dist: trusty
language: python
addons:
  postgresql: 9.4
  apt:
    packages:
      - libjpeg-dev
      - zlib1g-dev
      - python-software-properties
      - ghostscript
      - libxslt1-dev
      - binutils
      - libproj-dev
      - libgdal1-dev
      - gdal-bin
      - postgresql-9.4-postgis-2.1
      - postgresql-9.4-postgis-scripts
      - memcached
      - libmemcached-dev
cache:
  apt: true
  directories:
    - $HOME/.pip-cache/
python:
  - '2.7.10'
before_install:
  - export DEBIAN_FRONTEND=noninteractive;
   sudo -E apt-get -yq update &>> ~/apt-get-update.log;
   sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install postgresql-9.4-postgis-2.2
  - ./script/database/install_postgis onadata_test postgres 127.0.0.1
env:
  - TESTFOLDER="onadata/apps/main onadata/apps/api" 
  - TESTFOLDER="onadata/apps/logger onadata/apps/viewer onadata/apps/restservice onadata/apps/sms_support onadata/libs"
install:
  - pip install --upgrade pip
  - pip install -r requirements/base.pip --allow-all-external
  - pip install flake8
  - python manage.py migrate --noinput --settings=onadata.settings.travis_test
  # make ~/tmp dir writable for npm downloads
  - mkdir -p "$HOME/tmp"
  - if [[ "$TESTFOLDER" == onadata/apps/logger* ]] ; then chmod a+w $HOME/tmp ; fi
  - if [[ "$TESTFOLDER" == onadata/apps/logger* ]] ; then  npm install ; fi
  - if [[ "$TESTFOLDER" == onadata/apps/logger* ]] ; then bower install --force-latest ; fi
script:
  - python manage.py test $TESTFOLDER --noinput --settings=onadata.settings.travis_test
  - if [[ "$TESTFOLDER" == onadata/apps/logger* ]] ; then karma start onadata/libs/javascript/tests/karma.conf.js ; fi
notifications:
  email:
    - tech+travis@ona.io
